import Head from 'next/head';
import Image from 'next/image';
import Featured from '../components/Featured';
import ProductList from '../components/ProductList';
import styles from '../styles/Home.module.css';
import axios from 'axios';

export default function Home({ productList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>GD-Restaurent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <ProductList productList={productList} />
    </div>
  );
}

export const getServerSideProps = async () => {
  //const myCookie = ctx.req?.cookies || "";
  //let admin = false;

  //if (myCookie.token === process.env.TOKEN) {
  // admin = true;
  //}

  const res = await axios.get('http://localhost:3000/api/products');
  return {
    props: {
      productList: res.data,
      //admin,
    },
  };
};
